### ISSUE TITLE
Tech Feedback survey timing

### ISSUE THREAD

**Issue by nathantaber** [UltraID/Salesforce---ServiceCloud#3]
I noticed that customers are being sent the feedback surveys before we have even fixed their printers!

For example: actually 2 examples!
I sent the RMA, but then saw that in one case the customer had already completed his survey! (5 stars by the way ;)
In the other case the customer had just recieved his DHL labels.. and then the feedback was sent (I think we had waited a day fro the DHL labels out of despatch)
In both cases we have not yet even recieved their printers back, let alone fix and return them!

**Comment by ChrisPellegrino** [comment]
timing was pushed out and only sends on closed cases.
