### ISSUE TITLE
Product Family | updating needed

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#44]
Hi Chris..
Assigning you to this at first as I was a bit scared of bringing the system to its knees!!
Just looking at the product classes and think they need changing and separating out.

So, currently we have: 
- Direct to Card Printers
& OEM too
- Prima
- Lamination / Engraving

Michael and me had a quick look at changing it but not a quick fix and poss some chance of breaking other stuff...

I think it should ideally be:
- Direct to Card
- & oem
- Re-transfer
- Lamination
- Engraving

This is clearer and also is ready for optima and laminator, and any future engraving products..

Just not sure how to implement it :)

Thanks Chris.

**Comment by Mike-Johnston** [comment]
very doable, look into hopefully by end of week or when i get some downtime

Luke, you can shoulder watch if you like

**Comment by UltraIDTechnicalSupport** [comment]
Yeah OK.
