### ISSUE TITLE
Some changes to handling our loaners... (Shall I separate these for UK)

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#46]
I have been looking at our loaners and how they are handled.

Some ideas below for how we could change a few things, and which would help for Darren’s reports and managing the loaners too, and be a more accurate..
But, I think it may be different to how you guys work? So before I change anything.. here’s what we thought.

(NOTE: Loan = the loan record, like LN-00123.  Loan Serial = the actual loan printers serial number record)

So currently, when a loan gets marked as RECEIVED, there is a field update that sets the loan serial to Available.. 
I (for UK) would like to change this to:

Loan gets marked as received = sets the Loan Serial to Awaiting Preperation.
Loan gets marked as Shipped  = sets the Loan Serial to On Loan

Note – we (tech support) don’t deal with our loaners immediately. So they could sit on the shelf for a while before we turn them around, at which point we mark them as available manually. 

The Workflow Rule:
![wf rule](https://cloud.githubusercontent.com/assets/8257794/5721191/648c4d2e-9b26-11e4-8e21-f06798ab52f4.jpg)

 
The field update: 
![field update](https://cloud.githubusercontent.com/assets/8257794/5721192/6698334e-9b26-11e4-955e-cd78af7eb2ff.jpg)

So, can I add in to the picklist above
                Awaiting Preperation
                On Loan

Hope this makes sense…

I thought that the way you guys deal with loaners may be different.. so I could remove the printer available field update.
Then make 2 new printer available field updates based on the region, and do the above for UK, and leave as is for USA.

What say ye, Master Salesforce??

**Comment by ChrisPellegrino** [comment]
yes you can do that. Just do a UK specific one. Loans are separated by warehouse. So do a new work flow specific to the uk for loan receive. This should look exactly like the orignal except  when received and warehouse is weymouth then change this field to awaiting prep.  on the original flow we make it specific to the US by just adding the warehouse redmond.

**Comment by ChrisPellegrino** [comment]
i'll start working on it today. It will be called loan printer received UK. If I finish it i'll let you know.

**Comment by ChrisPellegrino** [comment]
OK I have finished the new workflow rule. called Loan: printer Received (UK) . Test it out over there to make sure it is firing correctly.

**Comment by ChrisPellegrino** [comment]
the question now is how are you going to change it to the status available after it has been worked on.

**Comment by UltraIDTechnicalSupport** [comment]
We will do it manually after we finished working on it...

I am going to carry on testing the rule's today (if I get chance!) I had to change a couple of bits..

[Luke]

**Comment by ChrisPellegrino** [comment]
this is finished
