### ISSUE TITLE
Remove status drop down/picklist from Ship & Receive Loan screen

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#48]
Hi Chris,
As discussed, these are the sections we thought could be removed from the Ship / Receive loan screen, as really it should just do it in the background -- ship it, or receive it. 

Sections highlighted in red could be removed:

![image](https://cloud.githubusercontent.com/assets/8257794/5799359/5f2e1496-9fc9-11e4-814f-80567a3fbd40.png)

![image](https://cloud.githubusercontent.com/assets/8257794/5799303/963dbf46-9fc8-11e4-8300-5b10bb927d51.png)

___________________________________________________
I think it will be done in here, but not 100%sure how:
SHIP LOAN VISUALFORCE Page:
https://ultracardsystems.my.salesforce.com/066d0000001bljG

RECEIVE LOAN VISUALFORCE page:
https://ultracardsystems.my.salesforce.com/066d0000001bljL

I made a clone to have a play with.. if I get chance.
ShipLoan Luke:
https://ultracardsystems.my.salesforce.com/066d0000001c709
____________________________________________________

GO SeaHawks!!! ;-)

**Comment by UltraIDTechnicalSupport** [comment]
Removing the field is easy..! Keeping the functionality of setting the status to Shipped... I think its over to you! :)

[Luke]

**Comment by UltraIDTechnicalSupport** [comment]
Also.. Karen in despatch showed me that the "sent out" date for shipping the loaner doesn't do anyting:

https://ultracardsystems.my.salesforce.com/066d0000001bljG

[Luke]

**Comment by ChrisPellegrino** [comment]
Ok i made head way on this.  I now have it to auto - set On Loan for the picklist. There will be no other choice. You have to click the date link next to the date field to populate the date field properly. then click save.  I will be changing receive loan, receive rma,  ship RMA,  to populate the staus fileds correctly. I have not found a way to populate the date automatically yet.

**Comment by ChrisPellegrino** [comment]
Actually this is done now. We wont foul with putting in the date automatically.

**Comment by UltraIDTechnicalSupport** [comment]
Cool.  That's perfect.
Also, I tried to fix the fact that despatch (weymouth) could not use the 'sent out' date... but I had to get Michael to help.  He found a tick box in permissions that fixed it :)

So all done.
