### ISSUE TITLE
Printer Serial number: Not Known Yet - Keeps changing

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#50]
Hey Chris...

So the Seahawks were close then... but not close enough :( 
Did you go to the game?  Didnt wind up in the paddy wagon then with your mate? haha...

So... as the title suggests  Printer Serial number: Not Known Yet - Keeps changing!
This is the latest change...
![image](https://cloud.githubusercontent.com/assets/8257794/6023856/0cd02570-abbf-11e4-9d4b-e94f35a2d8bf.png)

Alan had a case with Not Known Yet automatically entered as expected.
But, when he looked at the case today the serial had become 55C1786!

Thought I would add it to the GitHub list as Michael was interested too..

Cheers...
[Luke]

**Comment by ChrisPellegrino** [comment]
OK, so i locked down being able to change the serial number. I should not have to make it just for "Not Known Yet" but probably can. If someone complains then we know who is changing it. There should be no reason to change a serial number!

**Comment by ChrisPellegrino** [comment]
by the way only the system admins can change it.

**Comment by UltraIDTechnicalSupport** [comment]
Cool.
Spoke to Nick. the only thing he had done similar that day was updating the SOLD dates on a bunch of Paclin's recently sold printers...
He definitely didn't deliberately change the  Not Known Yet  serial record.
And this also happened a few weeks back when it became a 58C Rio Pro.....

Either way, will keep an eye on it..

Cheers.
[Luke]
