### ISSUE TITLE
Case creation flow 'position filed error' 

### ISSUE THREAD

**Issue by Mike-Johnston** [UltraID/Salesforce---ServiceCloud#51]
What I am trying to do is add a new contact to an existing account (UTC Fire & Security);

 

This bit is fine;

 
![image](https://cloud.githubusercontent.com/assets/5329316/6960978/0beaff26-d91f-11e4-9ebe-994fc7ab7c3b.png)

So is the next step;

 
![image](https://cloud.githubusercontent.com/assets/5329316/6960984/11c3554c-d91f-11e4-9114-19a383d42cc7.png)

![image](https://cloud.githubusercontent.com/assets/5329316/6960988/1968a7ca-d91f-11e4-8287-b48a27c75988.png)

But on the next step, the ‘Position’ field has changed from Tech Support’ to ‘None’. There are no other options in this drop-down list;

 
![image](https://cloud.githubusercontent.com/assets/5329316/6960997/26d5a4f8-d91f-11e4-89cf-1a4ec8290543.png)

You cannot progress beyond this step. Very frustrating;

**Comment by ChrisPellegrino** [comment]
Fixed the issue by actually just removing the postion pick list from this page. It is not needed and redundant.
