### ISSUE TITLE
Docusign replacement 

### ISSUE THREAD

**Issue by Mike-Johnston** [UltraID/Salesforce---ServiceCloud#53]
if memory recalls the docusign renewal is up in a few months

@ChrisPellegrino did you come-up with an idea for a suitable replacement to save some $$$

**Comment by ChrisPellegrino** [comment]
i have been looking at Right Signature. I have not started testing it yet.

https://appexchange.salesforce.com/listingDetail?listingId=a0N30000005vdIWEAY
