### ISSUE TITLE
Add Johnson & Shivakumar to Service Cloud

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#54]
Johnson needs to be added to SC.  We looked at this before Christmas briefly but it never really got implemented, I think we ran out of licences??

Also, Shivakumar holds a small stock of parts for Muffadal for ease of shipping in that region.
So Muffadal has asked if we can possibly add Shivakumar as an RMA option?

I think as we add Johnson, and poss Shiva, that we may well be better off by re arranging all the RMA / Cover Letter / Exchange email templates into regional folders....  Its gonna get messy in there else!

Chris, any thoughts??

Luke.

**Comment by ChrisPellegrino** [comment]
Johnson was added a long time ago. We will have to kick somebody to add shivakumar. 
It looks like these would be the people.  andy matko, liam miles,john H, andrew cornelius. Andy matko does not seem to use it at all. So thats my vote. You should talk to him about it first. 

I'm always for organizing.

**Comment by UltraIDTechnicalSupport** [comment]
Yeah Johnson is on there but wasn't it the case that as he is predominantly sales he needed different licence for Service Cloud?

I will try and get some spare time to just sit and look at all this stuff..

**Comment by ChrisPellegrino** [comment]
we don't use service cloud licenses anymore. We chose to just stick with salesforce default. Service cloud is just a skin layered on top which was not very good and expensive.  We can give him right to do both.
