### ISSUE TITLE
Docusign Status Updating the Shipped/Authorised field

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#55]
Hi Chris...

This could be a long story! So this is the short version:
Also, I don't think this is something I can edit?  and not sure exactly what would need to be changed..    here goes:

Sometimes (usually to get an exchange or loaner out in time for that days collection) we will send the docusign but then reset and print the paperwork.. then we can take the item down for shipping.

The Status is now READY TO SHIP.

Then, the customer completes docusign, which sets the status back to AUTHORISED.

If we don't then go back in and print the paperwork again (to set the status back to READY TO SHIP) Karen then cant mark it as shipped, as the status is back to AUTHORISED.

Now,
-We should spot it.. and we do mostly..  but we may be out on leave or similar..
-Karen/Rosie should have already marked it as shipped, but generally they just leave all the paperwork for days/weeks and catch up on it later - (don't go there!! this causes other issues too) ;-)

**MY QUESTION IS**
Can we add a field update rule to state that when the docusign is completed.. if the status is already READY TO SHIP, not to change it [back to authorized]?

If possible: great :-)

But, I suspect it may be more baked in than we may have access to though?

Whadyareckon???

**Comment by ChrisPellegrino** [comment]
interesting thought. I will look into it. Just off the top of my head i think i can do that.

**Comment by ChrisPellegrino** [comment]
I believe i have fixed this. There is a global work flow rule for docusign complete. What i have set is if the status is generated or sent and the docusign is completed then change to authorised. Therefore if the status is ready to ship and the docusign is completed it should not change. I'll test it through today to make sure.

**Comment by ChrisPellegrino** [comment]
the workflow rule was fixed and tested good.

**Comment by UltraIDTechnicalSupport** [comment]
Great.. Cheers Chris!
Will keep an eye on it here too..
Thanks again :)
Luke.

**Comment by UltraIDTechnicalSupport** [comment]
Hi Chris..  It did seem fixed.. but not sure now..

![image](https://cloud.githubusercontent.com/assets/8257794/8279785/2decd82a-18cf-11e5-8e07-3ab6949971a4.png)

Alan sent the docusign, then printed the paperwork to ship it that day, then the docusign came in and set it back to Authorized again.. so I just had Karen on the phone!!   Its easy to set it back, but hopefully we shouldn't need to...

Could you double check it again when you get chance?

Thanks Chris :)
Luke.

https://ultracardsystems.my.salesforce.com/a0kd000000D7cT2?srPos=0&srKp=a0k

**Comment by ChrisPellegrino** [comment]
I just checked the printer exchange. Not printhead exchange. I bet I missed that.

**Comment by UltraIDTechnicalSupport** [comment]
Hi Chris..   I think this is still updating the Exchange Status.. so Karen is unable to ship stuff, as the status changes from ready to ship whenj the docusign is done..

https://ultracardsystems.my.salesforce.com/a0kd000000F7bN0?srPos=0&srKp=a0k

When you chance, could you have a look?  Thanks Chris.

Note: I changed the buttons and wrote an email to the guys here about this (copied you in: Tue 30/06/2015 10:10)... I thought that if we did it in the order below, the status stayed as ready to ship:
1. send docushite
2. click manually authorise
3. Print paperwork..

So..  I wonder if in this exchange (link above) Nick clicked Manually Auth, then printed the paperwork, ....then sent the docusign..    So is this why it didnt work?

Cheers Chris!

**Comment by ChrisPellegrino** [comment]
yes this is why it did not work. in Nicks case it would set back to sent, then when customer signs it it would be set to authorized. There is no way around him doing it backwards. however maybe i can have Karen being able to ship something if it is set to authorized.

**Comment by ChrisPellegrino** [comment]
ok for some reason the workflow rule was not firing correctly. Now it seems to be. it think as a precaution i'm going to let karen ship if  set to  authorized.

**Comment by UltraIDTechnicalSupport** [comment]
OK Cool.. Thanks.
Karen can actually change the status to shipped.. she just didn't know she could.  But to be honest, the less steps she has to manually do then better ;-)
If she can ship stuff whatever the status, that's perfect.
Its only the docushite that affects it anyway... Its not like she is shipping something that hasn't already genuinely been sent (in that she usually does it later than the actual day that it did physically ship!)

**Comment by ChrisPellegrino** [comment]
She is able to ship now on authorized or ready to ship.  We will have to keep and eye on the workflow rule.
