### ISSUE TITLE
changing sent from notifications@ultra-identity.com 

### ISSUE THREAD

**Issue by Mike-Johnston** [UltraID/Salesforce---ServiceCloud#56]
looking to change this one to @ultraid.com

bad branding, mailbox does not technically exist ect 

@ChrisPellegrino can you think of any problems this might cause? anything that could stop working

![image](https://cloud.githubusercontent.com/assets/5329316/8720205/3beb5996-2ba9-11e5-82ed-0223fef6961a.png)

**Comment by Mike-Johnston** [comment]
correction, remove in general 

trying to track down any locations where it is used or mentioned in emails

**Comment by ChrisPellegrino** [comment]
no problem as far as i see removing it. that was the first one nathan created but then we change to notifications@ultraid.com.
