### ISSUE TITLE
Also scrap RMA from Opportunity custom button:  'Quote Rejected/ Printer Scrapped'

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#58]
![image](https://cloud.githubusercontent.com/assets/8257794/8721180/380e6fc8-2bb0-11e5-831e-3731c500def2.png)

Go Hawkes ;-)

Can we also set the related RMA to SCRAPPED from this button?

https://ultracardsystems.my.salesforce.com/00bd0000000eYrO?type=Opportunity&setupid=OpportunityLinks&retURL=%2Fp%2Fsetup%2Flink%2FActionButtonLinkList%3FpageName%3DOpportunity%26type%3DOpportunity%26setupid%3DOpportunityLinks%26retURL%3D%252Fui%252Fsetup%252FSetup%253Fsetupid%253DOpportunity

Ta.
Luke.

**Comment by ChrisPellegrino** [comment]
yeah that one is tricky. i have to think outside the box. I hate the quote and opportunity structure . it is a pain in my arse.

**Comment by UltraIDTechnicalSupport** [comment]
Hello,  Darren asked about this again..

I don't about the code, but is there a way to add in to set the related RMA# status to Scrapped?

I may ask the question on the forum....

**Comment by ChrisPellegrino** [comment]
This can not be done by a work flow but i can get around that by changing the button to a flow. i'm working on that right now.

**Comment by UltraIDTechnicalSupport** [comment]
Hello...
Just a thought:

What about just using a field update?
As if the OP is scrapped, then the RMA would also be scrapped.. 

Hmmmm... I cant get that to work.. I think because its cross object? 

I have tried field updates, worflow rules, process builder...  Grrrrrrr...
F@cking salesforce!!!   Everything is a massive ball ache!

Hope your flow works...
Cheers Chris...

**Comment by ChrisPellegrino** [comment]
yes if the  the two objects are not linked either by master to master or master or look up relationships then you can not use work flows. The only two ways that work are Triggers ( huge pain)  and visual flows. I already have the visual flow done.I need to set up the button and finish locations.  The flow will  set  the opportunity to scrapped/closed, the case to closed, the rma to scrapped-closed and the the serial number to scrapped. All in one swoop. I like Flows.

**Comment by ChrisPellegrino** [comment]
Ok my friend. I finished my magic. I tested it out. New button on the op is  Scrap Printer. 

Take a test drive. https://ultracardsystems.my.salesforce.com/006d000000a08mk

or go to OP 6152  then click Scrap Printer.   then check out the status of the opp, case,rma and  serial number. 

It is headless and not reversable. if you guys want it to be verfied first ( ie click ok to continue and reversable so you can set things back if you did the wrong one let me know) if not then we are done here. 


I love flows ( heart emoji here!)

**Comment by ChrisPellegrino** [comment]
extra note: I can do this to repairs to so that it closes the case when the repairs are finished. 

if you want to see the flow it is called scrap printer  > under create >workflow>flow> select active flow from drop down> click go > scroll down to scrap printer

**Comment by UltraIDTechnicalSupport** [comment]
Cool..
Tested with your OP (6152).  Perfik!
I will have a look through the flow, see if I can get my head around it...

Only anomaly I noticed was that after clicking the Scrap Printer button in the OP, the screen refreshed but just to a blank screen?  Poss a one off.

We will let you know how it goes on the next one Darren does..

Thanks for this again Chris!
![image](https://cloud.githubusercontent.com/assets/8257794/10535910/bb4d877c-73de-11e5-8624-7c8e7c1cd399.png)

**Comment by UltraIDTechnicalSupport** [comment]
Hi Chris,

Darren just tried to Scrap OP-6301 (link below) - but gets error of "Insufficient Privileges".
https://ultracardsystems.my.salesforce.com/006d000000bHWWh?srPos=0&srKp=006

I tried, and just get the next screen as blank with this in the address bar:
https://ultracardsystems--c.na14.visual.force.com/apex/Scrap_Printer?OpptID=006d000000bHWWh

Sorry.. Like you said before: this is a pain in your ass ;)
Luke.

**Comment by ChrisPellegrino** [comment]
i don't have the blank screen issue. I'll have to login in as you. The funny part is that is the correct URL. 
are you suing Chrome? it could be browser related. i do not get a flow error


for Darrens issue i think it is because he does not have the rights to change the status on one of the objects becuase i do not get a flow error which means it is running correctly.

i'll log in as him to see.  

They cleaned the gum wall after 20 years!!!  nasty job there. 

![image](https://cloud.githubusercontent.com/assets/8000610/11131824/6443518c-8941-11e5-85c7-58a66d81dbd4.png)

**Comment by ChrisPellegrino** [comment]
Ok i fixed both. 

for darren it was becuase i did not make the visual force page accessible to the service reps

thats under manage user>profiles>service rep>visual force page access. 

The reason why you were getting a blank page when you ran it was because in your user settings you had  development mode checked. this goes to the different url.
all is good now.
