### ISSUE TITLE
API Access for Alan to develop the DHL (UK) collections alongside the DHL API

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#59]
Hi Chris,

Can you help..

Alan is making progress with our new DHL collections idea...  but now needs permissions to access our salesforce API..  

I am not sure how to do it..

Will add more info later.. but at first we will need to just get info from SF, and then there will be field updates.. poss email templates.. etc..

What about creating a new user: DHL Automation
Or do I need to create a new user profile and permission set?
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_concepts_security.htm

Luke.

**Comment by ChrisPellegrino** [comment]
all service reps  already has api enabled.Here is a list of factors thought

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/calls.htm

what API is he using? here is the list for which ones he could use.

https://help.salesforce.com/HTViewHelpDoc?id=integrate_what_is_api.htm

you can just give him system admin permission set if you want to see if that gets
what he needs.

**Comment by ChrisPellegrino** [comment]
here is a better blurp about the api structure

https://developer.salesforce.com/page/Salesforce_APIs

**Comment by ChrisPellegrino** [comment]
another good read. i think he should be doing a REST API. 

https://developer.salesforce.com/blogs/tech-pubs/2011/10/salesforce-apis-what-they-are-when-to-use-them.html

**Comment by everthere** [comment]
From my experience with the support portal, I'd definitely support using REST over SOAP. Uses less bandwidth, it's faster and a lot less rigid.
