### ISSUE TITLE
Push Exchange info to Global Search

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#62]
Hi Chris..

I have not managed to get this to work?

[Global] Search for 61F1864 and there is no info on the Exchange that this printer was sent out under within the search results?  There is now a Note where I typed the serial, but the note came too late.
https://ultracardsystems.my.salesforce.com/a0kd000000H1cwu

I am trying to get the 'Exchange Replacement Item' field searchable too...

Reason:
Customer returned this exchange printer by mistake, they should have sent the faulty one! 
It arrived with no RMA.  When Darren searched for it, the exchange did not show up in the results.. costing more time to figure out what the printer was here for..

Any help?

GoHawkes
Luke :)

**Comment by ChrisPellegrino** [comment]
I never did that. I did the defective item.. I'll make the replacement item searchable though. 
The only way to make something searchable is to put it in a separate text field and set it to external.

**Comment by ChrisPellegrino** [comment]
ok you can now get a result on the global search.  Works on printers and printheads.

**Comment by UltraIDTechnicalSupport** [comment]
Didnt work?  Is the fix taking a BA flight across the Atlantic?

![image](https://cloud.githubusercontent.com/assets/8257794/11722436/9cced2f8-9f60-11e5-89cd-c8e54284cb7d.png)

**Comment by ChrisPellegrino** [comment]
It works . try it again.  i was messing with the numbers.
