### ISSUE TITLE
Update repairs fields ready for Helix repairs 

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#63]
Hi Chris,

We will need to update the repairs fields ready for the Helix..

Not sure if this will mean a different repairs flow if printer = Helix?
Or we can just update what we have already.
Darren recalls that you wanted to avoid having a load of junk in there originally, so Im wondering if a new Helix repair page/flow is the way to go...

Currently we have:
![image](https://cloud.githubusercontent.com/assets/8257794/14787243/77f887a2-0afa-11e6-930d-70c1dc8efec4.png)

We need:
 - Firmware
 - Printer Serial
 - Printhead Power
 - Roller Temperature
 - Horizontal
 - Vertical
 - Printhead Temp
 

Any thoughts?

Cheers Chris..
Luke.

**Comment by ChrisPellegrino** [comment]
I take a look and see what i can do. Do you mean printhead serial ?

**Comment by ChrisPellegrino** [comment]
So i took a look. It would take a lot of rework to separate it out. Although we should do this eventually for now i think we will just add those fields to the layouts. We also have to put them in the serial number  ones as well.  I'll start working on that. 

To separate them out i will need to build a whole new flow. Right now it is just a java script button with a bunch of IF Else statements . Flows are better and once i get the flow done and tested then we can do a proper separation.

**Comment by ChrisPellegrino** [comment]
I added all the stuff in the serial number and repair. 
i Just created all the fields for the Helix and put them under section Helix  and change the section for all other printers to DTC in both the serial number area and repairs area. I still need to do the wrokflow rules to update repairs to serial number current config and test it out.  Check it out and let me know if i missed something.

**Comment by UltraIDTechnicalSupport** [comment]
Hello,

I don't see the new Helix section?
![image](https://cloud.githubusercontent.com/assets/8257794/14811677/107971ee-0b91-11e6-8a92-178433192844.png)

I tried looking in different page layouts.. but cant see it.
Am using a dummy Helix in CASE 014861, RMA-0004878.

Could we do a different Page Layout for Helix? Would that work?

I see the new fields in setup. but not in the repairs page?

PS:
Added the word 'Offset' to horizontal and vertical fields

**Comment by ChrisPellegrino** [comment]
No you can't do a different page layout. A record type can only have one page layout and not multiple That means we have to create new record types, flows,page layout , work flow rules  etc. It can be done but that will take time.  I must have forgotten to save it. I put them back in there and saved it. You should see it now. 

![image](https://cloud.githubusercontent.com/assets/8000610/14823576/e595b5b8-0b87-11e6-869b-e8a1db06a8ed.png)

**Comment by ChrisPellegrino** [comment]
i have added all the fields and put in all the workflows needed and changed the page layouts for this. Closing
