### ISSUE TITLE
New case comment email alert - to Support email, instead of case owner

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#64]
Hello again Chris..

Hoping to achieve the above, but before I change anything I wanted to run it past you.

The current email alert and rule is here:
https://ultracardsystems.my.salesforce.com/01Wd0000000To4W/e?retURL=%2F01Wd0000000To4W
and
https://ultracardsystems.my.salesforce.com/01Qd0000000HgYS/e?retURL=%2F01Qd0000000HgYS

I have created a new USER - UK Tech Support  (005d00000054VQJ)  so I can use that just for its email (support@ultraid.com), 

But I am wary of tweaking the rule:
![image](https://cloud.githubusercontent.com/assets/8257794/14853817/f064073a-0c84-11e6-946e-a6dd27144fb1.png)

What I thought was that I could have a separate rule just for here (UK). and then a separate email alert.
Something like:
- new comment = true
- case owner = Luke, Darren, Dave, Nick or Alan

Any tips?

This has always been requested, as if one of us is away then the new case comment is not seen by anyone.
More important now as Dave is working a 3 day week.. so more chance of us missing his web created case comments.

Thanks Chris.

**Comment by UltraIDTechnicalSupport** [comment]
Actually.. same for the Loaner Docusign completed emails too..

Although we could setup and forwarder for these I suppose..?

**Comment by ChrisPellegrino** [comment]
First get rid of the user you do not need it and it cost 125 a month for each user. 

This new case comment is global so if you make it just to you then no one else in the world will get it

we have to make two at least. for US and for UK  and probably middle east as well.

Its best to clone it first and rename the new one New case comment - UK. 

For the rule  itself add case region  equals europe.
 so as the rule will read if there is a new comment and the case owner is not europe tech support but it is the europe region then it will fire.  below example. 

![image](https://cloud.githubusercontent.com/assets/8000610/14890632/52fd41a2-0d18-11e6-8be6-f2503256265e.png)



then go to edit the email alert. You need to remove the case owner. and in the addtional emails put in the support@ultraid.com and you can get rid of michael. 


https://www.dropbox.com/s/kimt2hzkybhx8jo/1.7.1%20ultra%20driver%20cd.zip?dl=0

after that dont forget to activate it and then deactivate the other one so you can test it. If it works then let me know and i will create ours .

**Comment by ChrisPellegrino** [comment]
oops this is the correct screen

https://www.dropbox.com/s/kimt2hzkybhx8jo/1.7.1%20ultra%20driver%20cd.zip?dl=0

**Comment by ChrisPellegrino** [comment]
https://ultracardsystems.my.salesforce.com/01Wd0000000To4W/e?px2=01Qd0000000HgYS&TableEnumOrId=Case&retURL=%2F_ui%2Fcore%2Fworkflow%2FWorkflowActionEditUi%3FruleId%3D01Qd0000000HgYS%26isNew%3D0%26retURL%3D%252F01Qd0000000HgYS

**Comment by ChrisPellegrino** [comment]
for loaners i think i found a way.  in the final step of the signing i can add  support@ultraid.com as the CC  so when the customer signs it your support email and whom ever sent it will get the complete signing email.

**Comment by ChrisPellegrino** [comment]
i did some testing and apparently the workflow rules we are looking at are not what is emailing us. 
i have them deactivated and i'm still getting case comments emails to my personal. Weird.

**Comment by ChrisPellegrino** [comment]
Ok I think i figured it all out. It was too much of a mess for you to do. So make an online web case yourself like you are a customer. Then in the europe queue set yourself as the case owner. Then as the customer add a comment on the web .  You should get an email to your personal and one to your support@ultraid.com.. Let me know if that works. It works here for the US one i made.

also what about Australia? Do we need to  have it go to your team. If you look at the rule i'm going by region now because it seems to be more reliable.

**Comment by UltraIDTechnicalSupport** [comment]
That's working perfectly Chris! Thanks for that..
Case comment notification goes to the case owner & to support@ultraid.com.
Its good.. 

I still haven't got my head around the Flows!

I already changed the Australasia support queue to come to us.
In fact now they all come to the UK except you guys (USA) and Muffadal's region.

I periodically go in and check all the other queues too, just in case.


Also, If the docusign emails are more tricky..  I have tried just adding a rule in my outlook which just forwards any duckusign system emails into support anyway.   So if this is preferable, we could just do that.

Thanks again Coach.

**Comment by Mike-Johnston** [comment]
alright Luke, take it im good to delete the UK tech support user?

**Comment by UltraIDTechnicalSupport** [comment]
Yep.  My bad.
I didnt realise we had to pay!

I was hoping to just use it for the email address alone.  sorry.

**Comment by UltraIDTechnicalSupport** [comment]
I was just about to delete it.. but will let you do it.. ;)

**Comment by Mike-Johnston** [comment]
And why don't you call my Coach :sob:

**Comment by UltraIDTechnicalSupport** [comment]
Ahhh, sorry.  I really should call you coach..  as actually Chris just goes in and fixes everything for me :)

**Comment by Mike-Johnston** [comment]
:fire: burn,

http://www.emoji-cheat-sheet.com/

**Comment by UltraIDTechnicalSupport** [comment]
Actually, thinking about the workflow rule for the UK...
Would this be more accurate:
![image](https://cloud.githubusercontent.com/assets/8257794/14911569/1007c9f4-0dee-11e6-97ad-98c12f405a30.png)

considering this:
I already changed the Australasia support queue to come to us.
In fact now they all come to the UK except you guys (USA) and Muffadal's region.

**Comment by ChrisPellegrino** [comment]
Who is the man!!! This guy right here! 

 After navigating the docusign labyrinth i have figured out how to get the completed docusign to your support email and to whomever sent it as well so if someone is out of the office it's covered.

quick overview mainly for Mr Johnston 

1) two loan templates- one for UK and one for US so they have different template ID's and last   steps.

2) UK  template last step is to CC support@ultraid.com
    US template last step is to CC ussupport@ultraid.com

3) Modified the send loan authorization button  javascript with if else statement

if equals Europe send UK template ID  else send The US template ID

BAAAM!!!   This is now live. 

I will be doing this for the exchange docusign as well. 

The only thing i can't figure out is why you have to click the button twice. But baby steps i guess.
