### ISSUE TITLE
Allow customers to add a Case Comment to a 'Closed' Web Case

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#67]
This would help us out, as currently if we close a case it means the customer can no longer add a case note.  This results in them raising a new case about the old case!  Then we waste our time faffing about with 2 cases..

Hopefully its possible :)

Thanks,
Luke.

**Comment by UltraIDTechnicalSupport** [comment]
PS...

it also means we have to close a case like this:

"
Hi Lorenz,

I am setting the case to closed, but that means you wouldn't be able to add a new comment.

So if you do need anything further please just email us directly, and include the case number in the email subject:

support@ultraid.com

Best Regards,
Luke.
"

**Comment by Mike-Johnston** [comment]
already raised on dev channel
